name: onboarding
description: Onboarding.

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_core:
    path: ../app_core
  meta: ^1.2.4

  #localize
  flutter_localizations:
    sdk: flutter

flutter:
  assets:
  #Lang
    - assets/lang/en.json
    - assets/lang/vi.json
    